// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/chocogem/bigquery-golang/pkg/api"
	"github.com/chocogem/bigquery-golang/pkg/api/handler"
	"github.com/chocogem/bigquery-golang/pkg/config"
	"github.com/chocogem/bigquery-golang/pkg/repository/adapter"
	adapter2 "github.com/chocogem/bigquery-golang/pkg/usecase/adapter"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.ServerHTTP, error) {
	userRepository, err := adapter.NewUserRepository(cfg)
	if err != nil {
		return nil, err
	}
	userUseCase := adapter2.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	handlers := &api.Handlers{
		UserHandler: userHandler,
	}
	serverHTTP := api.NewServerHTTP(handlers)
	return serverHTTP, nil
}
